services:
  - type: web
    name: pg-hostel-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        value: pg_hostel_secret_key_2026_hanmanth
      - key: NODE_ENV
        value: production
