services:
  - type: web
    name: pg-hostel-api
    runtime: node
    buildCommand: cd server && npm install
    startCommand: cd server && node seed.js && node server.js
    envVars:
      - key: JWT_SECRET
        value: pg_hostel_secret_key_2026_hanmanth
      - key: NODE_ENV
        value: production
